name: Cypress Tests

on: [push]   #This runs the workflow automatically for every push 

jobs:
  cypress-run:   #This defines a job that runs on Ubuntu.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository   #Gets the latest code from GitHub.
        uses: actions/checkout@v3

      - name: Install dependencies   #Installs dependencies needed for tests.
        run: npm install

      - name: Run Cypress tests   #Runs all Cypress tests automatically.
        run: npx cypress run