name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./cypress_ci_demo/package-lock.json

      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: npm ci
        working-directory: ./cypress_ci_demo

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./cypress_ci_demo
